### ISSUE TITLE
co2 alarm if co2 exceeds a specific value

### ISSUE THREAD

**Issue by daniel-fraubaum** [avollkopf/cbpi4-scd30-co2-sensor#2]
I have my fermentation controller with CBPI4 and also with an SCD30 sensor and the SCD30 based CO2 Sensor Plugin. 
Is it possible to configure an alarm if the co2 sensor exceeds an specific value? I also have the co2 gas bottle in the fermentation room, and I thougt it would be cool to use CBPI and the SCD30 Plugin also for alarms if the bottle leaks? alarm should only trigger an GPIO if an value is exceeded! on the GPIO I will connect an alarm buzzer with an red light and an very loud buzzer! 
Thanks, 
Daniel

**Comment by avollkopf** [comment]
Are you using mqtt sensors? I have added an alarm, if they don't respond for a defined time and a Notification will pop up on the screen that needs to be klicked. This will reset the alarm and another alarm will pop up again, if the sensor does not send data. 

This request could be realized in a similar way with a trigger limit of the Sensor value. Would that be working?

**Comment by daniel-fraubaum** [comment]
No, I'm not using mqtt sensors so far.

**Comment by avollkopf** [comment]
Please test development version on github. 

Alarmlimit added in Hardware settings:
![image](https://github.com/PiBrewing/cbpi4-scd30-co2-sensor/assets/43980694/2c757ee2-b63a-47df-9ca6-4ebf129a676c)

You need to activate 'Sensor Action' for your sensor reading in the dashboard config for your sensor to see the menu right of your sensor data (3 dots).
![image](https://github.com/PiBrewing/cbpi4-scd30-co2-sensor/assets/43980694/b5d8212b-444f-43a2-a815-e68edc03c55d)

If you click on the sensor menu, you can reset the alarm as Alarm will only pop up once or if value falls below limit and raises again:
![image](https://github.com/PiBrewing/cbpi4-scd30-co2-sensor/assets/43980694/c750e1fe-135f-44f6-ab83-2c9f8973dbc8)


Please report back, if this is working for you. Then I can release a new version also on pypi.org

**Comment by daniel-fraubaum** [comment]
Wow great! will test it this week! Currently upgrading to bookworm and so on! :-)

**Comment by daniel-fraubaum** [comment]
<img width="1094" alt="image" src="https://github.com/PiBrewing/cbpi4-scd30-co2-sensor/assets/33567257/fe58594b-bb5a-4bdd-a0e9-682b05ed5907">
Works great at my first test! :-) will connect hardware buzzer this week and let you know further! Thanks so much!!

**Comment by daniel-fraubaum** [comment]
ok it looks like the buzzer sound is only played once (for 1 second) and not permanent till alarm reset! is there a chance to implement an permanent playing till alarm reset?

**Comment by avollkopf** [comment]
This was the purpose. But I can add a parameter that the alarm goes off every new sensor reading, but not with the confirmation button as it would open too many windows in the browser

**Comment by daniel-fraubaum** [comment]
ok that sounds good! and sorry, maybe my wish was not clear at the beginning!

**Comment by avollkopf** [comment]
No worries, try 0.0.8.a4 and select Continuous as Alarmtype -> It'll also send notifications on every sensor reading if you have enabled PushNotifications (Can be annoying, but I can't separate it)

**Comment by avollkopf** [comment]
... an alarm is now triggered on every sensor reading (e.g. every 30 sec, if you have set the readings every 30 sec in the global settings for the SCD30 sensor)

**Comment by avollkopf** [comment]
.. and AlarmType 'Single' plays the alarm only once until it has been resetted or the value is falling below the limit and goes up again

**Comment by avollkopf** [comment]
.. and AlarmType 'Single' plays the alarm only once until it has been reseted or the value is falling below the limit and goes up again

**Comment by daniel-fraubaum** [comment]
oh man! that works great! thank you so much!!!

**Comment by avollkopf** [comment]
ok, I will release this version as 0.0.8 and close the issue
